// V7 endgame evaluation (Plan 03-04) — implements ENDG-01..05.
//
// New sister translation unit to eval.cpp. Called from evaluate() between
// the tempo block and the tapered combine (eval.cpp plan 03-04 hook).
//
// EVAL-10 / D-12 contract: NO hardcoded weight constants in this file.
// All adjustable values flow through v7::coeffs::* extern symbols defined
// in src/coeffs.cpp (generated from coeffs.json by tools/gen_coeffs.py).
//
// Translation units in this plan:
//   endgame.cpp (THIS FILE):  KPK probe, opposition, wrong-bishop+RP, fortress
//   kpk_bitbase.cpp (GITIGNORED): generated by tools/gen_kpk.py at build time
//
// References:
//   ENDG-01: kpk_is_win() — KPK bitbase O(1) bit lookup
//   ENDG-02: has_opposition() — direct opposition bonus
//   ENDG-03: is_wrong_bishop_rook_pawn_draw() — canonical draw recognition
//   ENDG-04: phase blend constants used in eval.cpp (endgame_limit/midgame_limit)
//   ENDG-05: is_fortress() — conservative fortress patterns behind UseFortressEval
//   D-11: fortress detection is default OFF; ship default ON only after
//         validation gauntlet shows clearly-positive Elo
//   D-12: all endgame coefficients in coeffs.json

#include "endgame.hpp"
#include "coeffs.hpp"
#include "board.hpp"
#include "movegen.hpp"

#include <algorithm>
#include <cstdint>

namespace v7 {

namespace {

// =============================================================================
// Square / geometry helpers (local to this TU)
// =============================================================================

inline int sq_file(Square sq) { return static_cast<int>(sq) & 7; }
inline int sq_rank(Square sq) { return static_cast<int>(sq) >> 3; }

// Chebyshev distance between two squares (maximum of file and rank delta).
inline int chebyshev(Square a, Square b) {
    return std::max(std::abs(sq_file(a) - sq_file(b)),
                    std::abs(sq_rank(a) - sq_rank(b)));
}

// Manhattan distance.
inline int manhattan(Square a, Square b) {
    return std::abs(sq_file(a) - sq_file(b)) + std::abs(sq_rank(a) - sq_rank(b));
}

// Mirror square horizontally (flip file within the same rank).
inline Square mirror_sq_h(Square sq) {
    return static_cast<Square>(static_cast<int>(sq) ^ 7);
}

// =============================================================================
// KPK index formula (Stockfish-style, RESEARCH.md Pitfall 5)
// =============================================================================
//
// Symmetry fold: if the pawn is on the right half of the board (file >= 4),
// mirror all three pieces horizontally so the pawn is always on files a-d.
// psq_idx = (rank_of(psq_norm) - 2) * 4 + file_of(psq_norm)  // 0..23
// index = stm | (bksq_norm << 1) | (wksq_norm << 7) | (psq_idx << 13)
//
// This produces indices in [0, 196608) — the KPK_BITBASE array has 24576
// bytes = 196608 bits. Illegal / out-of-range indices map to 0 (DRAW).

static inline int kpk_index_impl(Color stm, Square wksq, Square bksq, Square psq) {
    int pf = sq_file(psq);
    Square wk = wksq, bk = bksq, ps = psq;
    if (pf >= 4) {
        wk = mirror_sq_h(wk);
        bk = mirror_sq_h(bk);
        ps = mirror_sq_h(ps);
    }
    int pr = sq_rank(ps);
    int pf_n = sq_file(ps);
    int psq_idx = (pr - 2) * 4 + pf_n;  // rank 2-7, file 0-3 → index 0..23
    return static_cast<int>(stm) | (static_cast<int>(bk) << 1)
           | (static_cast<int>(wk) << 7) | (psq_idx << 13);
}

// =============================================================================
// Material identification helpers
// =============================================================================

// Count pieces of given type for given color.
inline int piece_count(const Board& b, Color c, Piece p) {
    return __builtin_popcountll(b.pieces_of(c, p));
}

// Is the bishop on a light square? Light squares = file+rank is even.
inline bool is_light_square(Square sq) {
    return ((sq_file(sq) + sq_rank(sq)) & 1) == 0;
}

// =============================================================================
// Fortress detection helpers (ENDG-05)
// =============================================================================
//
// Conservative set of well-known fortress patterns. Implements ≥2 canonical
// patterns per D-11. Returns true only for positions that are
// CANONICALLY recognized as drawn fortresses.
//
// Pattern 1: K+B vs K+R+P — bishop controls promotion square, rook/pawn
//   cannot make progress. Simplified: check if the weaker side has K+B and
//   the stronger side has K+R+P, and the bishop covers the promotion square.
//
// Pattern 2: K+N vs K+P — knight on a blockading square with king support,
//   defending king within reach of the pawn. Simplified: stalemate-like
//   fortress where the knight permanently blocks.
//
// Pattern 3: Locked pawn chains — identical pawn structures for both sides
//   with no breakthrough possible (symmetric or near-symmetric pawn masses
//   with no passed pawns on either side). Very conservative filter.

static bool is_fortress_kb_vs_krp(const Board& b) {
    // One side has K+B (only), other side has K+R+P (only).
    // Simplified: detect the K+B side, check if bishop controls promotion sq.
    for (Color weak = WHITE; weak <= BLACK; ++weak) {
        Color strong = static_cast<Color>(1 - weak);
        // Weak side: exactly K+B (no pawns, no rooks, no queens)
        if (piece_count(b, weak, BISHOP) != 1) continue;
        if (piece_count(b, weak, ROOK)   != 0) continue;
        if (piece_count(b, weak, QUEEN)  != 0) continue;
        if (piece_count(b, weak, PAWN)   != 0) continue;
        if (piece_count(b, weak, KNIGHT) != 0) continue;
        // Strong side: exactly K+R+P
        if (piece_count(b, strong, ROOK)  != 1) continue;
        if (piece_count(b, strong, PAWN)  != 1) continue;
        if (piece_count(b, strong, QUEEN) != 0) continue;
        if (piece_count(b, strong, BISHOP)!= 0) continue;
        if (piece_count(b, strong, KNIGHT)!= 0) continue;

        // Check if the pawn is a rook pawn (a or h file)
        Bitboard pawn_bb = b.pieces_of(strong, PAWN);
        Square psq = static_cast<Square>(__builtin_ctzll(pawn_bb));
        int pf = sq_file(psq);
        if (pf != 0 && pf != 7) continue;  // must be a/h-file rook pawn

        // Promotion square for strong side's pawn
        Square promo_sq;
        if (strong == WHITE) {
            promo_sq = static_cast<Square>(56 + pf);  // a8 or h8
        } else {
            promo_sq = static_cast<Square>(pf);  // a1 or h1
        }

        // Check bishop color matches promotion square
        Bitboard bish_bb = b.pieces_of(weak, BISHOP);
        Square bsq = static_cast<Square>(__builtin_ctzll(bish_bb));
        bool bishop_light = is_light_square(bsq);
        bool promo_light = is_light_square(promo_sq);

        // For K+B to hold as fortress: bishop controls promotion square
        // (same color as promotion square is required for the fortress to hold)
        if (bishop_light != promo_light) continue;

        // Weak king within reach of the promotion corner
        Square wk_sq = b.king_square(weak);
        if (chebyshev(wk_sq, promo_sq) <= 2) {
            return true;
        }
    }
    return false;
}

static bool is_fortress_kn_vs_kp(const Board& b) {
    // One side has K+N (only), other side has K+P (only).
    // Simplified fortress: knight permanently blocks the passed pawn.
    for (Color blocker = WHITE; blocker <= BLACK; ++blocker) {
        Color pusher = static_cast<Color>(1 - blocker);
        if (piece_count(b, blocker, KNIGHT) != 1) continue;
        if (piece_count(b, blocker, PAWN)   != 0) continue;
        if (piece_count(b, blocker, BISHOP) != 0) continue;
        if (piece_count(b, blocker, ROOK)   != 0) continue;
        if (piece_count(b, blocker, QUEEN)  != 0) continue;
        if (piece_count(b, pusher, PAWN)    != 1) continue;
        if (piece_count(b, pusher, KNIGHT)  != 0) continue;
        if (piece_count(b, pusher, BISHOP)  != 0) continue;
        if (piece_count(b, pusher, ROOK)    != 0) continue;
        if (piece_count(b, pusher, QUEEN)   != 0) continue;

        Bitboard pawn_bb = b.pieces_of(pusher, PAWN);
        Square psq = static_cast<Square>(__builtin_ctzll(pawn_bb));
        Bitboard knight_bb = b.pieces_of(blocker, KNIGHT);
        Square nsq = static_cast<Square>(__builtin_ctzll(knight_bb));

        // Knight directly in front of the pawn?
        Square in_front = (pusher == WHITE)
            ? static_cast<Square>(static_cast<int>(psq) + 8)
            : static_cast<Square>(static_cast<int>(psq) - 8);
        if (nsq != in_front) continue;

        // Blocker king within 2 squares of the knight to support it
        Square bk = b.king_square(blocker);
        if (chebyshev(bk, nsq) <= 2) {
            return true;
        }
    }
    return false;
}

static bool is_fortress_locked_pawns(const Board& b) {
    // Very conservative: both sides have identical pawn structure locked
    // head-to-head (each pawn faces an opposing pawn), no queens, no rooks.
    // This is a draw in practice but not always forced — flag conservatively.
    if (piece_count(b, WHITE, QUEEN) != 0) return false;
    if (piece_count(b, BLACK, QUEEN) != 0) return false;
    if (piece_count(b, WHITE, ROOK)  != 0) return false;
    if (piece_count(b, BLACK, ROOK)  != 0) return false;
    if (piece_count(b, WHITE, BISHOP)!= 0) return false;
    if (piece_count(b, BLACK, BISHOP)!= 0) return false;
    if (piece_count(b, WHITE, KNIGHT)!= 0) return false;
    if (piece_count(b, BLACK, KNIGHT)!= 0) return false;

    // Must have at least one pawn each
    Bitboard wp = b.pieces_of(WHITE, PAWN);
    Bitboard bp = b.pieces_of(BLACK, PAWN);
    if (!wp || !bp) return false;

    // Every white pawn must have a black pawn directly in front (locked chain)
    Bitboard wp_scan = wp;
    while (wp_scan) {
        int s = __builtin_ctzll(wp_scan);
        wp_scan &= wp_scan - 1;
        // Square directly in front for white pawn
        int front = s + 8;
        if (front > 63) return false;
        if (!(bp & (1ULL << front))) return false;
    }
    // Same check for black
    Bitboard bp_scan = bp;
    while (bp_scan) {
        int s = __builtin_ctzll(bp_scan);
        bp_scan &= bp_scan - 1;
        int front = s - 8;
        if (front < 0) return false;
        if (!(wp & (1ULL << front))) return false;
    }
    return true;
}

} // anonymous namespace


// =============================================================================
// Public API implementations
// =============================================================================

bool kpk_is_win(Color stm, Square wksq, Square bksq, Square psq) {
    int idx = kpk_index_impl(stm, wksq, bksq, psq);
    if (idx < 0 || idx >= 196608) return false;
    return (KPK_BITBASE[idx >> 3] >> (idx & 7)) & 1;
}

bool has_opposition(const Board& b, Color side) {
    // Direct opposition: kings on the same file or rank with exactly 1 square
    // between them (Chebyshev distance = 2, same file OR same rank),
    // AND it is the OTHER side's turn to move.
    // Also covers: same diagonal with 1 intermediate square (distance=2, diagonal).
    // Standard definition: kings on same rank or file with 1 square gap AND
    // other side to move = the given side has the opposition.
    if (b.side_to_move == side) return false;  // must be the OTHER side's turn

    Square ksq = b.king_square(side);
    Square opp_ksq = b.king_square(static_cast<Color>(1 - side));

    int df = std::abs(sq_file(ksq) - sq_file(opp_ksq));
    int dr = std::abs(sq_rank(ksq) - sq_rank(opp_ksq));

    // Direct opposition: 1 square apart on same rank or file (Chebyshev=1 → distance 1)
    // Wait: "odd number of squares between" = 1 means they are 2 squares apart (king-distance 2).
    // Wikipedia: "Direct opposition: kings facing each other with one square between them"
    // → kings are 2 squares apart on the same rank or file. df=0, dr=2 OR df=2, dr=0.
    // "Diagonal opposition" is when df==dr==2 (2 squares diagonally apart).
    if (df == 0 && dr == 2) return true;  // same file, 1 square between
    if (df == 2 && dr == 0) return true;  // same rank, 1 square between
    if (df == 2 && dr == 2) return true;  // diagonal opposition (2 diagonally apart)
    return false;
}

bool is_wrong_bishop_rook_pawn_draw(const Board& b) {
    // Pattern: one side has K + B + rook-pawn (a or h file); bishop is the
    // WRONG color for the promotion square; the defending king can reach the
    // promotion corner.
    for (Color attacker = WHITE; attacker <= BLACK; ++attacker) {
        Color defender = static_cast<Color>(1 - attacker);

        // Attacker must have exactly K + B + 1 pawn (the rook pawn), no other pieces
        if (piece_count(b, attacker, BISHOP) != 1) continue;
        if (piece_count(b, attacker, PAWN)   != 1) continue;
        if (piece_count(b, attacker, KNIGHT) != 0) continue;
        if (piece_count(b, attacker, ROOK)   != 0) continue;
        if (piece_count(b, attacker, QUEEN)  != 0) continue;

        // Defender must have only a king (K vs K+B+P)
        if (piece_count(b, defender, PAWN)   != 0) continue;
        if (piece_count(b, defender, KNIGHT) != 0) continue;
        if (piece_count(b, defender, BISHOP) != 0) continue;
        if (piece_count(b, defender, ROOK)   != 0) continue;
        if (piece_count(b, defender, QUEEN)  != 0) continue;

        // Pawn must be a rook pawn (a or h file)
        Bitboard pawn_bb = b.pieces_of(attacker, PAWN);
        Square psq = static_cast<Square>(__builtin_ctzll(pawn_bb));
        int pf = sq_file(psq);
        if (pf != 0 && pf != 7) continue;

        // Promotion square for the attacker
        Square promo_sq;
        if (attacker == WHITE) {
            promo_sq = static_cast<Square>(56 + pf);  // a8 or h8
        } else {
            promo_sq = static_cast<Square>(pf);  // a1 or h1
        }

        // Bishop color and promotion square color
        Bitboard bish_bb = b.pieces_of(attacker, BISHOP);
        Square bsq = static_cast<Square>(__builtin_ctzll(bish_bb));
        bool bishop_light = is_light_square(bsq);
        bool promo_light = is_light_square(promo_sq);

        // Wrong bishop: bishop cannot control the promotion square
        if (bishop_light == promo_light) continue;  // right color — can win

        // Defending king can reach the promotion corner
        Square def_king = b.king_square(defender);
        // Pawn distance to promotion (number of ranks to advance)
        int pawn_rank = sq_rank(psq);
        int promo_rank = sq_rank(promo_sq);
        int pawn_dist = std::abs(promo_rank - pawn_rank);
        // King distance to promotion corner
        int king_dist = chebyshev(def_king, promo_sq);
        // Defender can reach the promotion corner in time?
        // Canonical check: king_dist <= pawn_dist + 1 (with side to move adjustment)
        int extra = (b.side_to_move == defender) ? 0 : 1;
        if (king_dist <= pawn_dist + extra) {
            return true;
        }
    }
    return false;
}

bool is_fortress(const Board& b) {
    // Conservative pattern set (ENDG-05, D-11):
    // Only returns true for CANONICALLY recognized fortress positions.
    if (is_fortress_kb_vs_krp(b)) return true;
    if (is_fortress_kn_vs_kp(b))  return true;
    if (is_fortress_locked_pawns(b)) return true;
    return false;
}

void endgame_eval(const Board& b, int& mg, int& eg, int phase, bool fortress_enabled) {
    // ---- Fortress detection (ENDG-05) — default OFF per D-11 ---------------
    // Bypassed completely when fortress_enabled = false (zero cost path).
    if (fortress_enabled && is_fortress(b)) {
        mg = v7::coeffs::fortress_score;
        eg = v7::coeffs::fortress_score;
        return;  // short-circuit: known draw
    }

    // ---- Wrong-bishop + rook-pawn draw (ENDG-03) ----------------------------
    if (is_wrong_bishop_rook_pawn_draw(b)) {
        // Scale eg toward DRAW using wrong_bishop_rp_scale.
        // Scale = 0: full draw (multiply by 0); Scale = 256: no change.
        eg = (eg * v7::coeffs::wrong_bishop_rp_scale) / 256;
        mg = (mg * v7::coeffs::wrong_bishop_rp_scale) / 256;
        return;
    }

    // ---- KPK probe (ENDG-01) ------------------------------------------------
    // Detect KPK material signature: one side has K+P, other has only K.
    for (Color stronger = WHITE; stronger <= BLACK; ++stronger) {
        Color weaker = static_cast<Color>(1 - stronger);
        if (piece_count(b, stronger, PAWN)   != 1) continue;
        if (piece_count(b, stronger, KNIGHT) != 0) continue;
        if (piece_count(b, stronger, BISHOP) != 0) continue;
        if (piece_count(b, stronger, ROOK)   != 0) continue;
        if (piece_count(b, stronger, QUEEN)  != 0) continue;
        if (piece_count(b, weaker, PAWN)     != 0) continue;
        if (piece_count(b, weaker, KNIGHT)   != 0) continue;
        if (piece_count(b, weaker, BISHOP)   != 0) continue;
        if (piece_count(b, weaker, ROOK)     != 0) continue;
        if (piece_count(b, weaker, QUEEN)    != 0) continue;

        // Pure KPK position found
        Square wksq = b.king_square(stronger);
        Square bksq = b.king_square(weaker);
        Bitboard pawn_bb = b.pieces_of(stronger, PAWN);
        Square psq = static_cast<Square>(__builtin_ctzll(pawn_bb));

        // Normalize: kpk_is_win expects white = the side with the pawn
        // If stronger == BLACK, flip everything for the KPK lookup
        Color stm = b.side_to_move;
        bool is_win;
        if (stronger == WHITE) {
            is_win = kpk_is_win(stm, wksq, bksq, psq);
        } else {
            // Flip colors: "white" = stronger (BLACK side), flip stm
            Color flipped_stm = static_cast<Color>(1 - stm);
            // In the KPK table, WHITE always has the pawn.
            // bksq becomes wksq for the flipped query.
            is_win = kpk_is_win(flipped_stm, bksq, wksq, psq);
        }

        if (!is_win) {
            // Known draw: zero out both scores
            mg = 0;
            eg = 0;
        } else {
            // Known win: assign a large endgame score for the stronger side
            // Use a 5-pawn equivalent as the KPK winning bonus (tunable).
            constexpr int KPK_WIN_SCORE = 500;  // cp
            int sign = (stronger == b.side_to_move) ? 1 : -1;
            eg = sign * KPK_WIN_SCORE;
            mg = sign * KPK_WIN_SCORE;
        }
        return;
    }

    // ---- Opposition eval (ENDG-02) ------------------------------------------
    // Apply opposition_value bonus for the side that has the opposition.
    // Only meaningful in endgame positions (phase < 64 = roughly below 25% midgame).
    if (phase < 64) {
        for (Color side = WHITE; side <= BLACK; ++side) {
            if (has_opposition(b, side)) {
                int bonus = v7::coeffs::opposition_value;
                int sign = (side == WHITE) ? 1 : -1;
                // Apply primarily to the endgame score where it matters most.
                eg += sign * bonus;
                break;
            }
        }
    }
}

} // namespace v7
