#!/usr/bin/env python3
"""Codegen: coeffs.json -> src/coeffs.cpp.

D-10: this script is the build-time codegen invoked by V7's CMake
add_custom_command (pre-staged by Plan 02 task 3 in CMakeLists.txt). It
transforms the human-edited single source of truth (coeffs.json) into a
C++ translation unit defining `extern const int ...` symbols in the
v7::coeffs namespace.

D-13: output is byte-deterministic across machines and across reruns on
the same input. The contract is:

  - sorted(data.keys()) — iterate top-level JSON keys in sorted order
  - skip any key beginning with `_` (meta keys)
  - for dict values: iterate sorted(val.keys()) and emit `{key}_{subkey}`
    symbols (scalar values become `extern const int X = N;`, list values
    become `extern const int X[N] = { ... };`)
  - for list values: emit `extern const int {key}[N] = { ... };`
  - for scalar values: emit `extern const int {key} = N;`
  - explicit LF line endings on output (CRLF stripped at write time)
  - sized arrays — the size in `int X[N]` matches the JSON list length

The corresponding `extern const int ...` forward declarations live in
include/coeffs.hpp; the set must match what this script emits or the
v7_engine link step will fail. include/coeffs.hpp is hand-maintained
alongside this script — the test suite (tests/test_v7_eval.py
test_coeffs_codegen_deterministic + test_coeffs_json_schema) catches
drift.

Usage:
    python3 gen_coeffs.py <coeffs.json> <output.cpp>

Only the Python stdlib is used (json, sys, pathlib) — no extra deps so
the codegen runs cleanly inside the CMake build with whatever Python
pybind11 already located.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


HEADER_TEMPLATE = (
    "// GENERATED by tools/gen_coeffs.py — DO NOT EDIT\n"
    "// Source: {source}\n"
    "//\n"
    "// This translation unit defines every v7::coeffs::* symbol forward-\n"
    "// declared in include/coeffs.hpp. Regenerated automatically by V7's\n"
    "// CMake build whenever coeffs.json changes (D-11). Not committed to\n"
    "// git (D-12).\n"
    "\n"
    '#include "coeffs.hpp"\n'
    "\n"
    "namespace v7::coeffs {\n"
    "\n"
)

FOOTER = "\n} // namespace v7::coeffs\n"


def _emit_scalar(name: str, value: int) -> str:
    return f"const int {name} = {int(value)};\n"


def _emit_array(name: str, values) -> str:
    nums = [str(int(v)) for v in values]
    body = ", ".join(nums)
    return f"const int {name}[{len(nums)}] = {{ {body} }};\n"


def _emit_key(key: str, value) -> str:
    """Emit one or more `extern const int` lines for a top-level key."""
    if isinstance(value, dict):
        # Dict values: emit {key}_{subkey} for each subkey in sorted order.
        out = []
        for subkey in sorted(value.keys()):
            sub = value[subkey]
            sym = f"{key}_{subkey}"
            if isinstance(sub, list):
                out.append(_emit_array(sym, sub))
            elif isinstance(sub, (int, bool)):
                out.append(_emit_scalar(sym, sub))
            else:
                raise TypeError(
                    f"Unsupported sub-value type for {key}.{subkey}: {type(sub).__name__}"
                )
        return "".join(out)
    if isinstance(value, list):
        return _emit_array(key, value)
    if isinstance(value, (int, bool)):
        return _emit_scalar(key, value)
    raise TypeError(f"Unsupported top-level value type for {key}: {type(value).__name__}")


def generate(coeffs_json_path: Path, output_cpp_path: Path) -> None:
    raw = coeffs_json_path.read_bytes()
    data = json.loads(raw.decode("utf-8"))

    body_parts = [HEADER_TEMPLATE.format(source=coeffs_json_path.as_posix())]
    for key in sorted(data.keys()):
        if key.startswith("_"):
            continue
        body_parts.append(_emit_key(key, data[key]))
    body_parts.append(FOOTER)

    text = "".join(body_parts)
    # D-13: explicit LF line endings, regardless of host OS.
    output_cpp_path.write_bytes(text.encode("utf-8").replace(b"\r\n", b"\n"))


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        sys.stderr.write(
            f"usage: {argv[0]} <coeffs.json> <output.cpp>\n"
        )
        return 2
    src = Path(argv[1])
    dst = Path(argv[2])
    if not src.is_file():
        sys.stderr.write(f"gen_coeffs.py: input not found: {src}\n")
        return 1
    dst.parent.mkdir(parents=True, exist_ok=True)
    generate(src, dst)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
