#pragma once

// =============================================================================
// V7 ENDGAME EVALUATION (Plan 03-04)
// =============================================================================
//
// New sister translation unit to eval.cpp, implementing ENDG-01..05:
//
//   ENDG-01: KPK bitbase O(1) probe (kpk_is_win) — runtime lookup into
//            the table generated by tools/gen_kpk.py at build time.
//   ENDG-02: Opposition evaluation (has_opposition) — applies
//            v7::coeffs::opposition_value bonus for the side with opposition
//            in K vs K+P endings.
//   ENDG-03: Wrong-bishop + rook-pawn draw (is_wrong_bishop_rook_pawn_draw)
//            — returns true when the position is a canonical drawing fortress.
//   ENDG-04: Continuous 0..256 phase blend — formulas live in eval.cpp using
//            v7::coeffs::endgame_limit and midgame_limit from coeffs.json.
//   ENDG-05: Fortress detection (is_fortress) — behind UCI toggle
//            UseFortressEval default OFF per D-11.
//
// Public entry: endgame_eval(board, mg, eg, phase) is called from eval.cpp
// between the tempo block and the tapered combine. It may adjust mg/eg
// in-place or short-circuit (e.g., returning DRAW_SCORE for known draws).
//
// EVAL-10 / D-12 contract: NO hardcoded weight constants in endgame.cpp.
// All adjustable values flow through v7::coeffs::* extern symbols defined
// in src/coeffs.cpp (generated from coeffs.json by tools/gen_coeffs.py).
//
// KPK table: KPK_BITBASE is declared here and defined in kpk_bitbase.cpp
// (gitignored, emitted by tools/gen_kpk.py at build time via CMake
// add_custom_command). See CMakeLists.txt KPK_CPP block.

#include "board.hpp"
#include <cstdint>

namespace v7 {

// =============================================================================
// KPK bitbase (generated by tools/gen_kpk.py — defined in kpk_bitbase.cpp)
// =============================================================================
//
// Table size: 24576 bytes = 196608 bits, indexed by:
//   normalize: if pawn file >= 4, mirror wksq/bksq/psq horizontally
//   psq_idx = (rank_of(psq_norm) - 2) * 4 + file_of(psq_norm)  // 0..23
//   idx = stm | (bksq_norm << 1) | (wksq_norm << 7) | (psq_idx << 13)
//   probe: (KPK_BITBASE[idx >> 3] >> (idx & 7)) & 1
//
// kpk_bitbase.cpp is gitignored (D-10/D-12 — mirrors coeffs.cpp pattern).
extern const uint8_t KPK_BITBASE[24576];

// =============================================================================
// Public endgame helpers (tested independently via pytest)
// =============================================================================

// kpk_is_win: return true if the KPK position (stm, wksq, bksq, psq) is a
// WIN for white (the side with the pawn). stm = WHITE (0) or BLACK (1).
// Applies the Stockfish-style symmetry fold and bit-lookup into KPK_BITBASE.
bool kpk_is_win(Color stm, Square wksq, Square bksq, Square psq);

// has_opposition: return true if the given side has the direct opposition
// (kings on the same file or rank with an odd number of squares between them
// AND it is the OTHER side's turn to move).
// ENDG-02: applies v7::coeffs::opposition_value bonus in endgame_eval().
bool has_opposition(const Board& b, Color side);

// is_wrong_bishop_rook_pawn_draw: return true when one side has K + B + rook-pawn
// (a-file or h-file pawn) with the WRONG color bishop for the promotion square,
// and the defending king can reach the promotion corner.
// ENDG-03: when true, endgame_eval() scales the score toward DRAW using
// v7::coeffs::wrong_bishop_rp_scale.
bool is_wrong_bishop_rook_pawn_draw(const Board& b);

// is_fortress: conservative pattern-based fortress detection.
// Returns true only for positions that are CANONICALLY recognized as fortresses.
// ENDG-05: only consulted when UseFortressEval is enabled (default OFF per D-11).
bool is_fortress(const Board& b);

// =============================================================================
// Public entry: called from eval.cpp between tempo block and tapered combine
// =============================================================================
//
// Signature: endgame_eval(board, mg, eg, phase, fortress_enabled)
//   - board:            position being evaluated (read-only)
//   - mg, eg:           midgame/endgame scores to adjust in place
//   - phase:            0..256 phase value (256 = full midgame, 0 = bare kings)
//   - fortress_enabled: value of options.UseFortressEval (D-11)
//
// Short-circuit semantics: if a known-drawn or known-won endgame is detected,
// sets mg = eg = DRAW_SCORE (0) or a WIN_SCORE and returns. Otherwise adjusts
// mg/eg additively (e.g., opposition bonus).
void endgame_eval(const Board& b, int& mg, int& eg, int phase,
                  bool fortress_enabled = false);

} // namespace v7
